# Generated by Django 3.2.12 on 2022-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='todonote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
